'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ACCOUNTPROFILE
    Public Property ADDRESS As String
    Public Property PASSWORD As String
    Public Property USERID As String
    Public Property ACCOUNTID As Long
    Public Property EMAIL As String
    Public Property CREDITCARD As String
    Public Property FULLNAME As String
    Public Property SALT As String

End Class
