'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ACCOUNT
    Public Property CREATIONDATE As Nullable(Of Date)
    Public Property OPENBALANCE As Nullable(Of Decimal)
    Public Property LOGOUTCOUNT As Integer
    Public Property BALANCE As Nullable(Of Decimal)
    Public Property ACCOUNTID As Long
    Public Property LASTLOGIN As Nullable(Of Date)
    Public Property LOGINCOUNT As Integer
    Public Property PROFILE_USERID As String

End Class
