'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ACCOUNTDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ACCOUNTDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ACCOUNTs() As DbSet(Of ACCOUNT)
    Public Overridable Property ACCOUNTPROFILEs() As DbSet(Of ACCOUNTPROFILE)
    Public Overridable Property HOLDINGs() As DbSet(Of HOLDING)
    Public Overridable Property ORDERS() As DbSet(Of ORDER)

End Class
