'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOLDING
    Public Property PURCHASEPRICE As Nullable(Of Decimal)
    Public Property HOLDINGID As System.Guid
    Public Property QUANTITY As Double
    Public Property PURCHASEDATE As Nullable(Of Date)
    Public Property ACCOUNT_ACCOUNTID As Long
    Public Property QUOTE_SYMBOL As String
    Public Property USERID As String

End Class
