'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ORDER
    Public Property ORDERFEE As Nullable(Of Decimal)
    Public Property COMPLETIONDATE As Nullable(Of Date)
    Public Property ORDERTYPE As String
    Public Property ORDERSTATUS As String
    Public Property PRICE As Nullable(Of Decimal)
    Public Property QUANTITY As Double
    Public Property OPENDATE As Nullable(Of Date)
    Public Property ORDERID As System.Guid
    Public Property ACCOUNT_ACCOUNTID As Long
    Public Property QUOTE_SYMBOL As String
    Public Property HOLDING_HOLDINGID As Nullable(Of System.Guid)
    Public Property USERID As String

End Class
