'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QUOTE
    Public Property LOW As Nullable(Of Decimal)
    Public Property OPEN1 As Nullable(Of Decimal)
    Public Property VOLUME As Double
    Public Property PRICE As Nullable(Of Decimal)
    Public Property HIGH As Nullable(Of Decimal)
    Public Property COMPANYNAME As String
    Public Property SYMBOL As String
    Public Property CHANGE1 As Double
    Public Property QUOTEID As Long

End Class
